
#Definimos el tipo de base de datos
quarkus.datasource.db-kind=postgresql

#Usuario y contraseña para acceder a la base de datos
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

#URL de conexión a la base de datos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2_db

#Sincroniza el codigo con la base de datos
quarkus.hibernate-orm.database.generation=update


quarkus.hibernate-orm.log.sql=true

quarkus.hibernate-orm.sql-load-script=Import.sql

